import { AdaptiveQuestionSelector } from "./adaptive.js";
import type { LLMProvider } from "./llm/provider.js";
import type {
  AdaptiveStrategy,
  AnswerAnalysis,
  CandidateRecord,
  GeneratedQuestion,
  Question,
  QuestionGenerationContext,
  Session,
} from "./types.js";

export interface GeneratedQuestionResult {
  question: Question;
  strategy: AdaptiveStrategy;
  reason: string;
  isGenerated: boolean;
}

export class QuestionGenerator {
  constructor(private provider?: LLMProvider | null) {}

  async generateNextQuestion(
    context: QuestionGenerationContext,
    session: Session,
    candidateRecord?: CandidateRecord | null,
    maxAttempts = 3,
  ): Promise<GeneratedQuestionResult> {
    const askedTexts = session.turns
      .map((t) => t.questionText)
      .filter((txt): txt is string => Boolean(txt && txt.trim()));

    context.askedQuestionTexts = askedTexts;

    // Attempt LLM question generation if provider is available
    if (this.provider && typeof this.provider.generateQuestion === "function") {
      for (let attempt = 1; attempt <= maxAttempts; attempt++) {
        try {
          const generated: GeneratedQuestion | null = await this.provider.generateQuestion(
            context,
          );

          if (generated && generated.question) {
            const questionId = `gen_d${context.day}_q${session.turns.length + 1}`;
            const questionObj: Question = {
              id: questionId,
              day: context.day,
              dayTitle: context.dayTitle,
              topic: generated.topic || context.topic,
              question: generated.question,
              difficulty: generated.difficulty || context.targetDifficulty,
              tags: [context.topic.toLowerCase().replace(/[^\w]/g, "-")],
            };

            if (process.env.NODE_ENV !== "production") {
              console.log(
                `[QuestionGenerator Dev Log] Attempt ${attempt}/${maxAttempts} succeeded. Generated question: "${generated.question.slice(
                  0,
                  80,
                )}..." | Strategy: ${context.strategy} | Difficulty: ${generated.difficulty}`,
              );
            }

            return {
              question: questionObj,
              strategy: context.strategy,
              reason: generated.reason || "Dynamically generated by LLM interviewer.",
              isGenerated: true,
            };
          }
        } catch (err: unknown) {
          if (process.env.NODE_ENV !== "production") {
            const msg = err instanceof Error ? err.message : String(err);
            console.error(
              `[QuestionGenerator Dev Error] Attempt ${attempt}/${maxAttempts} failed: ${msg}`,
            );
          }
        }
      }
    }

    // Deterministic Predefined Question Fallback
    if (process.env.NODE_ENV !== "production") {
      console.log(
        "[QuestionGenerator Dev Fallback] Dynamic LLM generation unavailable or failed max attempts. Falling back to predefined question bank selector.",
      );
    }

    const fallbackSelector = new AdaptiveQuestionSelector(this.provider);
    const fallbackDecision = await fallbackSelector.selectNextQuestion(
      session,
      context.lastAnalysis,
      candidateRecord,
    );

    return {
      question: fallbackDecision.selectedQuestion,
      strategy: fallbackDecision.strategy,
      reason: `[Fallback] ${fallbackDecision.reason}`,
      isGenerated: false,
    };
  }
}
